SCENARIOS = [
    {"name":"Yadroviy urush","description":"Dunyoda yadroviy zarbalar bo'lib, radiatsiya yuqori.","water_months":24,"food_months":18,"has_electricity":True,"has_medical":True,"special_condition":"Texnik mutaxassislar muhim.","capacity_formula":"half"},
    {"name":"Pandemiya","description":"Mutant virus tarqaldi.","water_months":12,"food_months":10,"has_electricity":True,"has_medical":True,"special_condition":"Tibbiyot xodimlari ustuvor.","capacity_formula":"half"},
    {"name":"Meteor zarba","description":"Meteor urilishi oqibatida chang buluti osmonni to'sdi.","water_months":16,"food_months":8,"has_electricity":False,"has_medical":True,"special_condition":"Fermer va agronom zarur.","capacity_formula":"half"},
    {"name":"Iqlim faloqati","description":"Keskin iqlim o'zgarishi yashashni qiyinlashtirdi.","water_months":20,"food_months":12,"has_electricity":False,"has_medical":True,"special_condition":"Suvni tejash rejimi.","capacity_formula":"half"},
    {"name":"Zombi apokalipsisi","description":"Infeksiya zombi to'dalarini paydo qildi.","water_months":10,"food_months":9,"has_electricity":False,"has_medical":False,"special_condition":"Harbiy va himoya ko'nikmasi muhim.","capacity_formula":"half"},
    {"name":"AI isyoni","description":"Sun'iy intellekt infratuzilmani egallab oldi.","water_months":14,"food_months":14,"has_electricity":True,"has_medical":False,"special_condition":"IT va elektronika mutaxassisi kerak.","capacity_formula":"half"},
    {"name":"Vulqon otilishi","description":"Super vulqon kul buluti bilan quyoshni to'sdi.","water_months":18,"food_months":11,"has_electricity":False,"has_medical":True,"special_condition":"Nafas olish tizimi xavfi.","capacity_formula":"half"},
    {"name":"Dengiz sathi ko'tarilishi","description":"Quruqlikning katta qismi suv ostida qoldi.","water_months":8,"food_months":15,"has_electricity":True,"has_medical":True,"special_condition":"Navigator va logistlar foydali.","capacity_formula":"half"},
    {"name":"Quyosh bo'roni","description":"Geomagnit bo'ron barcha elektronikani ishdan chiqardi.","water_months":11,"food_months":10,"has_electricity":False,"has_medical":True,"special_condition":"Mexanik bilimlar kerak.","capacity_formula":"half"},
    {"name":"Kimyoviy halokat","description":"Zaharli gazlar shaharlarga tarqaldi.","water_months":13,"food_months":9,"has_electricity":True,"has_medical":True,"special_condition":"Kimyo bo'yicha bilim zarur.","capacity_formula":"half"},
    {"name":"Global urush","description":"Davlatlararo urushdan keyin ta'minot uzildi.","water_months":15,"food_months":7,"has_electricity":False,"has_medical":False,"special_condition":"Liderlik va intizom muhim.","capacity_formula":"half"},
    {"name":"Qora sovuq","description":"Yadro qishi tufayli harorat keskin tushdi.","water_months":9,"food_months":8,"has_electricity":True,"has_medical":False,"special_condition":"Issiqlik ishlab chiqarish tajribasi kerak.","capacity_formula":"half"},
    {"name":"Genetik ofat","description":"Eksperiment sabab ovqat ekinlari nobud bo'ldi.","water_months":14,"food_months":6,"has_electricity":True,"has_medical":True,"special_condition":"Biolog va agronom kerak.","capacity_formula":"half"},
    {"name":"Kiberqulash","description":"Raqamli tizimlar qulashi sabab aloqa yo'qoldi.","water_months":12,"food_months":12,"has_electricity":True,"has_medical":False,"special_condition":"Radio aloqa mutaxassisi muhim.","capacity_formula":"half"},
    {"name":"Kosmik chang davri","description":"Atmosferadagi chang Quyosh nurlarini to'sdi.","water_months":17,"food_months":10,"has_electricity":False,"has_medical":True,"special_condition":"Oziq-ovqatni uzoq saqlash kerak.","capacity_formula":"half"}
]
